name: Docker Build Test and Push DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v*
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}

        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}       

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: type=semver,pattern={{major}}.{{minor}}
          labels: ${{ steps.meta.outputs.labels }}



      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
    # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/argocd-test-app:{{major}}.{{minor}}.

